name: Nuget Publishment

on:
  workflow_dispatch:

jobs:
  test-service:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v3
      with: 
        submodules: true
        
    - name: build-service
      if: ${{ steps.pull-carbon-aware-sdk.continue }} == 1
      run: dotnet build ./src/Greenhopper.sln
      
      # todo: run tests
      
    - name: build-sample
      if: ${{ steps.pull-carbon-aware-sdk.continue }} == 1
      run: dotnet build ./sample/timer-trigger/CarbonAware.AzureFunction.Sample.sln
      
  pack-service:
    needs: [test-service]
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout
      uses: actions/checkout@v3
      with: 
        submodules: true
        
    - name: pack
      run: |    
        pushd ./src/Greenhopper/
        dotnet build -c Release
        dotnet pack -c Release
        popd
        
    - name: upload-artifacts
      uses: actions/upload-artifact@v3
      with:
        path: ./**/*.nupkg
        
  push-nuget:      
      needs: [pack-service]
      runs-on: ubuntu-latest
      steps:
      
      - name: download-artifact
        uses: actions/download-artifact@v3
        with:
          path: ./
   
      - name: nuget-setip
        uses: NuGet/setup-nuget@v1.1.1
    
      - name: Publish
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}

