name: Release New Nuget

on:
  push:
    branches: [ release/* ]
    paths: src/**
  workflow_dispatch:

env:
    PROJECT_NAME: CarbonAware.AzureFunction.Services

jobs:
  test-service:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v3
      with: 
        submodules: true
        
    - name: build-service
      if: ${{ steps.pull-carbon-aware-sdk.continue }} == 1
      run: dotnet build ./src/${{ env.PROJECT_NAME }}.sln
      
      # todo: run tests
      
    - name: build-sample
      if: ${{ steps.pull-carbon-aware-sdk.continue }} == 1
      run: dotnet build ./sample/timer-trigger/CarbonAware.AzureFunction.Sample.sln
      
  pack-service:
    needs: [test-service]
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout
      uses: actions/checkout@v3
      with: 
        submodules: true
        
    - name: pack
      run: |    
        version=$(echo ${GITHUB_REF#refs/heads/}
        packid="${{ env.PROJECT_NAME }}.${version}.nupkg"
        echo $packid
        pushd ./src/${{ env.PROJECT_NAME }}/
        dotnet build -c Release
        dotnet pack -c Release -p:PackageID=packid
        popd
        
    - name: upload-artifacts
      uses: actions/upload-artifact@v3
      with:
        path: ./src/${{ env.PROJECT_NAME }}/*.nupkg
        
  push-nuget:      
      needs: [pack-service]
      runs-on: ubuntu-latest
      steps:
      
      - name: download-artifact
        uses: actions/download-artifact@v3
        with:
          path: ./
    
      #- name: push-nuget
      #  run: |   
      #      dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/OWNER/index.json"

